### ISSUE TITLE
Embed Italian translation into website

### ISSUE THREAD

**Issue by csparpa** [reactivemanifesto/website-manifesto#36]
What should be done:
- embed markdown (README and glossary)
- check that links are working and/or adjust them

**Comment by rasummer** [comment]
@csparpa I'm currently adding the translation to the website. Could you be kind enough to translate some of the website UI elements as outlined in the following spreadsheet: https://docs.google.com/spreadsheets/d/1Z_rA48AWXa1SjyR2n-vGqRKpGk124LtfdbpAOG-38cU/edit?usp=sharing

**Comment by csparpa** [comment]
Sure thing, will do it as soon as I can

Claudio Sparpaglione

**Comment by rasummer** [comment]
thanks

**Comment by csparpa** [comment]
@rasummer I've translated the lemmas

**Comment by rasummer** [comment]
thank you
