### ISSUE TITLE
The Chinese Version's [Revision Suggestion] link is broken, should fix

### ISSUE THREAD

**Issue by pimgeek** [reactivemanifesto/website-manifesto#59]
![image](https://user-images.githubusercontent.com/1609306/29257222-d452b446-80e2-11e7-955a-f6c12bb65111.png)

- Current URL - https://github.com/reactivemanifesto/reactivemanifesto/blob/master/README.zh-CN.md
- Correct URL - https://github.com/reactivemanifesto/reactivemanifesto/blob/master/README.zh-cn.md

**Comment by jroper** [comment]
This was fixed by renaming on the other end:

https://github.com/reactivemanifesto/reactivemanifesto/commit/276e5e15420d62b2a5d2cd6a1644e916678a1d11#diff-0d10b069ec2726b1e9d0c0b0eae34f3e
