### ISSUE TITLE
Fix deprecated use of GitHub API

### ISSUE THREAD

**Issue by jroper** [reactivemanifesto/website-manifesto#82]
Received this email from GitHub:

> Hello there!
> 
> On February 3rd, 2020 at 22:35 (UTC) your application (The Reactive Manifesto) used an access token (with the User-Agent AHC/2.0) as part of a query parameter to access an endpoint through the GitHub API.
> 
> https://api.github.com/user
> 
> Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.
> 
> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
> 
> Thanks,
> The GitHub Team

Fixing the `access_token` query parameter is trivial, however there's another deprecated authentication mechanism that we use, where we authenticate not as a user but as the application itself using the `client_id` and `client_secret`, we do this so that we're not limited by the anonymous access rate limits which are far too low for what we need when we do name/avatar reconciliation. Using query parameters for this is listed as deprecated in the deprecation notice, however the actual page that documents it still shows the deprecated method, and there's no documentation anywhere that I can see on how to migrate to a non deprecated method of authentication. So I've raised a GitHub support request to get that sorted, and then I'll push fixes either way.

/cc @jboner

**Comment by jboner** [comment]
Thanks for acting on this, James.

**Comment by jroper** [comment]
GitHub support hasn't got back to me, but I did a quick test and saw that client_id/client_secret can be passed as HTTP basic credentials. I've committed this, and we should stop getting deprecation notifications.
