### ISSUE TITLE
Cannot to sign The Reactive Manifest with GitHub

### ISSUE THREAD

**Issue by slima4** [reactivemanifesto/website-manifesto#91]
When I tried to sign the manifest using GitHub for this purpose, I got an error:

`'access_token' is undefined on object: {"error":"bad_verification_code","error_description":"The code passed is incorrect or expired.","error_uri":"https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#bad-verification-code"}`

**Comment by sebastian-alfers** [comment]
Hi @slima4, thank you for the report.

May I ask you to try again if it works now? I just successfully unsigned and signed again with my personal account, and it works.

**Comment by slima4** [comment]
Hi @sebastian-alfers 

For now, everything works fine.

Thanks!

**Comment by sebastian-alfers** [comment]
Great, thanks a lot for getting back to us!
